Build(deps-dev): Bump cypress from 9.1.0 to 9.1.1 (PR #2101)
Bumps [cypress](https://github.com/cypress-io/cypress) from 9.1.0 to 9.1.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a href="https://github.com/cypress-io/cypress/releases">cypress's releases</a>.</em></p>
<blockquote>
<h2>9.1.1</h2>
<p><em>Released 12/03/2021</em></p>
<p><strong>Bugfixes:</strong></p>
<ul>
<li>Fixed a regression in <a href="https://docs.cypress.io/guides/references/changelog#9-1-0">9.1.0</a> where our
built binary didn't contain patches to some dependencies. Addressed in
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/pull/19239">#19239</a>. This fixed some
issues including:
<ul>
<li>Requests containing <code>~</code> will no longer be improperly encoded. Fixes
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19083">#19083</a>,
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19084">#19084</a>,
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19115">#19115</a>,
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19096">#19096</a>,
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19178">#19178</a>.</li>
<li>A TypeError displaying <code>data.hasOwnProperty is not a function</code> will no
longer throw in some situations. Fixes
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19091">#19091</a>.</li>
<li>Empty extra hooks will no longer be sent as data when recording to the
Dashboard. Fixes
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19087">#19087</a>.</li>
<li>The Runner hanging when baseUrl is set to null to load a local file. Fixes
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19105">#19105</a></li>
</ul>
</li>
<li>When using the default configuration of <code>&quot;nodeVersion&quot;: &quot;system&quot;</code> with an
installed system node &gt;=17, Cypress will now work properly rather than throw
an error incorrectly pointing to the user's plugin file. Fixes
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/18914">#18914</a>.</li>
<li>Shadow DOM elements no longer error as hidden during actionability when the
element is covered by its parent shadow root. Fixes
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/18008">#18008</a>.</li>
<li>When using <code>.type()</code> events now correctly propagate out of the shadow DOM.
Fixes <a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/17531">#17531</a>.</li>
<li>The <code>this</code> context is now properly preserved when overwriting <code>cy.clock()</code>.
Fixes <a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19158">#19158</a>.</li>
</ul>
<p><strong>Dependencies:</strong></p>
<ul>
<li>Upgraded <code>@cypress/request</code> from <code>2.88.7</code> to <code>2.88.10</code>. Addressed in
<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19099">#19099</a>.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a href="https://github.com/cypress-io/cypress/commit/a64b72a5da5b4031765c721817733b971dd760eb"><code>a64b72a</code></a> release 9.1.1</li>
<li><a href="https://github.com/cypress-io/cypress/commit/8262f80d1f8ca72ef4317fc191811f6a46497184"><code>8262f80</code></a> fix: patch-package is not applied in dist'ed build (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19239">#19239</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/11e99fc35a4cf1fe43abed07cd3f7fb2441fa461"><code>11e99fc</code></a> chore: fix flaky tests (net stubbing, websocket, proxy logging, Firefox syste...</li>
<li><a href="https://github.com/cypress-io/cypress/commit/4d35779c8ada80c999537bf9c6d7649c01ff5bad"><code>4d35779</code></a> chore: Clean up CircleCI Configuraiton (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19212">#19212</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/6b15468579b539cd6f6bf3049fdc3ad8a1a414a3"><code>6b15468</code></a> chore: Migrate Windows Tests from Appveyor to CircleCI (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19037">#19037</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/f85c736d3e493ec052cf6c94e25854ccf279ac30"><code>f85c736</code></a> fix: text events propagate out of shadow root. (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19132">#19132</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/6b19381f7949476b164f64c684c636f4743b98e3"><code>6b19381</code></a> fix: Add support for system node 17 (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19094">#19094</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/4630ef49d846de529e85372fe892fd6a537fe1a6"><code>4630ef4</code></a> fix: set the context when overwriting .clock command (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19158">#19158</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/42dfb8abb11921322486467a563902fb870aca6c"><code>42dfb8a</code></a> docs: add info around next version, testing other projects (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19157">#19157</a>)</li>
<li><a href="https://github.com/cypress-io/cypress/commit/2c9cb68450ab0f1fc072e5cf6e21f517ba555039"><code>2c9cb68</code></a> feat: adding recommended VSCode plugins to workspace (<a href="https://github-redirect.dependabot.com/cypress-io/cypress/issues/19146">#19146</a>)</li>
<li>Additional commits viewable in <a href="https://github.com/cypress-io/cypress/compare/v9.1.0...v9.1.1">compare view</a></li>
</ul>
</details>
<br />

[![Dependabot compatibility score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=cypress&package-manager=npm_and_yarn&previous-version=9.1.0&new-version=9.1.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't alter it yourself. You can also trigger a rebase manually by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)

</details>